### ISSUE TITLE
Use scroll to directive

### ISSUE THREAD

**Issue by lucassus** [9ci/angle-grinder#137]
see https://github.com/scottcorgan/angular-scrollto or write better implementation

**Comment by alexeyzvegintcev** [comment]
added https://github.com/oblador/angular-scroll and applied it to docs
Also, created directive for side-menu to make it fixed on the screen

**Comment by basejump** [comment]
now that you know the new strategy. can you rework this to go against the 1.x branch in AG. Thanks

**Comment by basejump** [comment]
@alexeyzvegintcev how do we test this? I'm not sure what this is for

**Comment by philarq** [comment]
I just read through the REAMDME.md in the original github link, and I suspect this is what's causing all the jumpiness between payment and paymentDetail grids on arBatch show screen.  it wastes time, it's disorienting  and  I'm surprised the AAP users haven't complained more.  

@jdabal @basejump I think we need a design meeting about using this feature smarter, less, or not at all.

**Comment by philarq** [comment]
I just read through the REAMDME.md in the original github link, and I suspect this is what's causing all the jumpiness between payment and paymentDetail grids on arBatch show screen.  it wastes time, it's disorienting  and  I'm surprised the AAP users haven't complained more.  

@jdabal @basejump I think we need a design meeting about using this feature smarter, less, or not at all.

**Comment by basejump** [comment]
we need to setup a screen share to undertand what this.
