### ISSUE TITLE
Advanced search form, re-enable the search button on the server side error

### ISSUE THREAD

**Issue by lucassus** [9ci/angle-grinder#175]
![sc3](https://cloud.githubusercontent.com/assets/41239/3130726/54607228-e7fc-11e3-9415-2ccfc5cb8714.gif)

**Comment by basejump** [comment]
is this still a valid open issue?

**Comment by aShevc** [comment]
works fine for me

**Comment by philarq** [comment]
there's no error on quick search, or when searching by fields.  searching by lastPayDate doesn't give any results though, probably a data issue.
