### ISSUE TITLE
Select2 is deprecated, try to replace it with ui-select

### ISSUE THREAD

**Issue by lucassus** [9ci/angle-grinder#210]
see 
- https://github.com/angular-ui/ui-select2
- https://github.com/angular-ui/ui-select
- https://github.com/angular-ui/ui-select/wiki/Roadmap (many feature are not ready jet)

**Comment by basejump** [comment]
@alexeyzvegintcev is this relevant? is select2 deprecated or do we use our own?

**Comment by alexeyzvegintcev** [comment]
@basejump we use our own ag-select wich is wrapper for ui-select2

**Comment by alexeyzvegintcev** [comment]
ui-select2 is also deprecated
review 
https://github.com/angular-ui/ui-select

**Comment by basejump** [comment]
perhaps we just copy over or fork what we want from https://github.com/angular-ui/ui-select2.
select 2 is most certainly not deprecated. https://select2.github.io/. its way more powerful too than the ui-select

**Comment by jdabal** [comment]
isn't it teh same as https://github.com/9ci/rcm/issues/2185 ?

**Comment by alexeyzvegintcev** [comment]
it is related, but not the same this issue is to change all selects with another implementation and #2185 - is fix one bug for selects

**Comment by alexeyzvegintcev** [comment]
@basejump I've reviewed ui-select API - it requires a lot of changes if we want to migrate to it, so I suggest to fork ui-select2 and make fixes there if we need something
