### ISSUE TITLE
Collapsed panel

### ISSUE THREAD

**Issue by jdabal** [9ci/angle-grinder#215]
user should be able to hide/show panel. Panel can have 3 stages: collapsed, normal or full page. When panel is collapsed it can have an option to show summary information - columns should be configurable.
![screen shot 2015-03-13 at 8 54 14 am](https://cloud.githubusercontent.com/assets/421237/6639542/994cf4f8-c95e-11e4-8ff3-a3cfc998863c.png)

![screen shot 2015-03-13 at 8 54 59 am](https://cloud.githubusercontent.com/assets/421237/6639551/a8f2ce46-c95e-11e4-8541-df4d01c34581.png)

**Comment by jdabal** [comment]
there are two concepts - panel with form view vs panel with grid.

There are 3 stages panel can be:
icon- collapse - the way it's now

icon- collapse - top - (minimize) - form display top row or redo a form with single space , smaller size. If grid -display one row

icon - expand - full screen


http://screencast.com/t/6SZaGY6h

http://screencast.com/t/P5GbhBoRIn

**Comment by jdabal** [comment]
new video with voice: http://screencast.com/t/MSjjYFcCD

**Comment by philarq** [comment]
this isn't in today's build with new angle-grinder.

http://screencast.com/t/0KIkRWm8Y2yd

**Comment by philarq** [comment]
have never seen the buttons that enable this.  Is there some special add to external config. I even removed my RCMAppSetupConfig in case it was overriding such a change, but still no collapse button.

**Comment by philarq** [comment]
Tests OK, except for the Collapse-Top only works for middle (Payment) panel: it displays the first row. For Batch and PD, it cuts off the first row.

**Comment by aShevc** [comment]
@phil for grids it leaves only selected row, for forms(edit panels) on Collapse-Top it  hides all fields except specified(can be configurable in RcmAppConfig).
Could you provide some information about what is expected behaviour?

**Comment by philarq** [comment]
For the batch info top panel, we want collapse-top to show the first info on each column, should be BatchID, PostedDate, Lockbox.  For payment and PD grids it should show the top row of grid.  Works for payment, but PD grid fails.

in config file, there's this, but lockbox isn't visible after collapse:

[
                            name: "lockbox",
                            model: "batch.lockBox",
                            label: "Lockbox",
                            from: "nine.ar.Lockbox.list()",
                            optionsKey: "lockboxNumber",
                            optionsValue: "lockboxNumber",
                            type: "select2local",
							stayOnCollapse: true
                    ],

**Comment by aShevc** [comment]
requires changes in grinder and rcm
for grids on Collapse-Top it shows selected row(we need this for payment grid because PD grid is depends on row that is selected in Payments), and first if nothing is selected

**Comment by philarq** [comment]
tests OK
