### ISSUE TITLE
enahancements to grid footer

### ISSUE THREAD

**Issue by jdabal** [9ci/angle-grinder#218]
add pager on the bottom of the grid - # of rows and totals for amount field . Amount columns should be configurable to sum them up.

Grid pager should have : Rows 1-20 of TotalRowCount

right now we have: 
![screen shot 2015-03-13 at 8 48 12 am](https://cloud.githubusercontent.com/assets/421237/6639452/e0de67f8-c95d-11e4-9b73-4bf4a3d5a522.png)

**Comment by basejump** [comment]
![screenshot 2015-03-26 04 28 34](https://cloud.githubusercontent.com/assets/187726/6843427/de5824f2-d370-11e4-95f6-cd9da7aa6372.png)

**Comment by basejump** [comment]
make it say "records 1 - 50 of 6679" for example. can be right aligned
