### ISSUE TITLE
Single spacing for forms

### ISSUE THREAD

**Issue by aShevc** [9ci/angle-grinder#244]

**Comment by aShevc** [comment]
![singlespasingedit](https://cloud.githubusercontent.com/assets/1845935/9112525/af76b432-3c57-11e5-8038-0dd93f17700f.png)

**Comment by basejump** [comment]
look here
https://www.dropbox.com/s/7nne9r7l5pszk6y/Screenshot%202015-08-06%2008.28.16.png?dl=0

**Comment by aShevc** [comment]
nav tabs fixed in rcm, single spacing - pushed to grinder master

**Comment by basejump** [comment]
should have been closed by https://github.com/9ci/angle-grinder/pull/246
