### ISSUE TITLE
Gridz footer css

### ISSUE THREAD

**Issue by basejump** [9ci/angle-grinder#280]
change from this
![image](https://cloud.githubusercontent.com/assets/187726/11491411/36ace03e-97a7-11e5-8c81-c867fd36444f.png)
 to this
![image](https://cloud.githubusercontent.com/assets/187726/11491499/fd307162-97a7-11e5-8745-b4063d46aad0.png)

and this
![image](https://cloud.githubusercontent.com/assets/187726/11491529/62d65ad6-97a8-11e5-815f-187173fb759d.png)

basically remove the border from the td and tr for the footer totals. also note the padding to be the same as the uper grider so the totals line up.

**Comment by basejump** [comment]
see note above on the padding so it lines up.
![image](https://cloud.githubusercontent.com/assets/187726/11577017/5a8ee296-99e0-11e5-832d-29af9793c414.png)

![image](https://cloud.githubusercontent.com/assets/187726/11577019/5cc682da-99e0-11e5-9a6a-37f33df10ff1.png)

**Comment by jdabal** [comment]
@alexeyzvegintcev can you right align amounts in Total footer so they are the same as column amounts ?
![screen shot 2016-03-29 at 1 40 43 pm](https://cloud.githubusercontent.com/assets/421237/14119493/fb69082a-f5b3-11e5-9112-2578021edb63.png)
