### ISSUE TITLE
phantomjs error

### ISSUE THREAD

**Issue by basejump** [9ci/angle-grinder#349]
grunt is not working and running tests on my local box following the instructions in README

![image](https://cloud.githubusercontent.com/assets/187726/19673224/7f987ec6-9a43-11e6-9ff3-c58ce3e05456.png)
 I have version 2.1.1 installed. not sure whats going on
![image](https://cloud.githubusercontent.com/assets/187726/19673234/8cf71dca-9a43-11e6-8fcc-7b25407b67a9.png)

**Comment by alexeyzvegintcev** [comment]
@basejump  fixed, please delete bower folder and make bower install, the issue was in dependencies, I've made changes for 1.x and merged it to  all braches (up to grails3)
