### ISSUE TITLE
get up to date with latest angular js 1.5.8

### ISSUE THREAD

**Issue by basejump** [9ci/angle-grinder#350]
https://code.angularjs.org/1.5.8/docs/guide/migration

We are pretty far behind with 1.4.7

**Comment by alexeyzvegintcev** [comment]
@basejump  angular 1.6 is already released https://docs.angularjs.org/guide/migration#migrating-from-1-5-to-1-6

**Comment by alexeyzvegintcev** [comment]
@basejump do we want to update for Grails 2.5.5 first?

**Comment by snimavat** [comment]
@alexeyzvegintcev grinder is already on 2.5.5 !

**Comment by alexeyzvegintcev** [comment]
@snimavat I know, the question is do we want update ag-grinder with new angular for Grail 2.5.5 first or for Grails 3.2.3
