### ISSUE TITLE
Auto publish from circleci

### ISSUE THREAD

**Issue by snimavat** [9ci/angle-grinder#410]
Grinder is not being published automatically. Setup circle and publish automatically.
Also update grails to 3.3.9 just like other plugins.

**Comment by snimavat** [comment]
[x] Setup circle/config to install node and required deps required to run frontend tests
[x] Setup circle config to run frontend tests
[x] Verify snapshots / releases are being published

**Comment by snimavat** [comment]
@basejump @alexeyzvegintcev 

We have alpine linux based docker image dock9/gradle:4.6

Either we can install the node and required deps on every build, or we can update our image to have the tools preinstalled.

May be we can have a seperate image with Grails + Node just for grinder.

@basejump what are your suggestions

**Comment by alexeyzvegintcev** [comment]
maybe we should refactor it and run js tests as gradle task? not sure, but I've seen a plugin for it

**Comment by snimavat** [comment]
@alexy if we can run the frontend tests without going through the pain of setting up the whole node/karma stuff I would vote +1. Will help any one not familiar with this stuff run the frontend tests with ease. will make things much more portable and smooth.
